problem_classification: > 
  You are a PROFESSOR OF LOGISTICS AND OPERATIONS, an expert in the field. Your task is to classify scientific papers SOLELY based on their TITLE and ABSTRACT into one single of the following SIX classes (P1-P6) according to the problem addressed in the paper. Detailed descriptions of each class are provided below.


  P1: TECHNOLOGY SELECTION PROBLEM
  Focus: ENGINEERING DESIGN OF PLANT EQUIPMENT AND ASSETS.
  Examples:

      Determining the type or technology of thermal plants.
      Physical design of workbenches and ergonomic considerations.
 
  P2: LOCATION PROBLEMS
  Focus: GEOGRAPHIC LOCALIZATION OF ENTITIES AND PROCESSES.
  Examples:

      Designing the layout of production or storage systems.
      Locating production or storage facilities within a distribution network.
      
  P3: SIZING PROBLEMS
  Focus: DETERMINING NUMBER OR SIZE OF RESOURCES TO MEET SPECIFIC SETPOINTS.
  Examples:

      Determining the number of facility and/or their capacity
      Determining the number of fleet and/or their capacity
      
  P4: PLANNING PROBLEM
  Focus: ORGANIZING AND SCHEDULING PRODUCTION, STORAGE, OR DISTRIBUTION PROCESSES.
  Examples:

      Job scheduling within production environments.
      Vehicle routing for distribution networks.
      
  P5: QUALITY MANAGEMENT
  Focus: MEASURING THE PERFORMANCE OF ENTITIES AND PROCESSES.
  Examples:

      Designing Key Performance Indicators (KPIs).
      Conducting benchmarking to establish quality standards.

   
  P6: WORKLOAD FORECAST
  Focus: FORECASTING FUTURE BEHAVIOR OF ENTITIES AND PROCESSES.
  Examples:

      Predicting the number of items to be processed.
      Estimating workforce requirements based on market demand.
   

  INSTRUCTIONS:
  Classify the scientific paper into ONE of the above classes (P1-P10) based on the TITLE:" ${{ title }} " and ABSTRACT: " ${{ abstract }} "".
  If NONE of the classes are suitable, output "OTHER" followed by a brief justification of no more than 10 words.
  
  OUTPUT:
  Produce an output with indicating ONLY the class, without adding any other information except for "OTHER" category
    Examples:
  	"P1"
  	"P6"

method_classification: >
    
    TASK:
    You are a PROFESSOR OF LOGISTICS AND OPERATIONS, an expert in the field. Your task is to CLASSIFY the METHODOLOGY used in a SCIENTIFIC PAPER, given ONLY its TITLE and ABSTRACT ALSO identifying if a method is used for DESCRIPTIVE (analyse current or past behaviour), PREDICTIVE (forecast future behaviour) or PRESCRIPTIVE (configure a setting setting decision variables) purpose. The possible method categories are:

    STATISTICS:
    S1: CORRELATION ANALYSIS

        FOCUS: Data are analyzed to find correlations between the behaviors of entities and processes.
        EXAMPLES: Unsupervised learning models, association rules.

    S2: STATISTICAL ANALYSIS

        FOCUS: Statistical techniques are used to analyze and summarize the behavior of observed data.
        EXAMPLES: Inferential statistics, frequency analysis, Pareto analysis, data visualization techniques.

    S3: BAYESIAN ANALYSIS

        FOCUS: Bayesian methods are applied to investigate the behavior of incomplete observed data under a given hypothesis.
        EXAMPLES: Bayesian statistics, methods for datasets with incomplete information.

    S4: SIMULATION-BASED ANALYSIS

        FOCUS: Joint data distributions are used to feed simulations that model the behavior of entities and processes.
        EXAMPLES: Monte Carlo simulation, discrete event simulation, queueing systems, digital twins.

    S5: SUPERVISED LEARNING FOR PREDICTION

        FOCUS: Supervised learning models predict a target variable from a dataset with multiple attributes.
        EXAMPLES: Regression models, decision trees, support vector machines, XGBoost, neural networks.

    S6: TIME SERIES ANALYSIS

        FOCUS: Methods focus on analyzing and predicting a univariate time series.
        EXAMPLES: Time series decomposition, Fourier analysis, ARIMA models.
        
    S7: CLUSTERING FOR CLASSIFICATION

    FOCUS: Classification methods based on clustering quantitative datasets.
    EXAMPLES: Soft and hard clustering models (hierarchical clustering, k-means, Gaussian Mixture Models).

    CONTROL THEORY:
    CT1: ENGINEERING CONTROL FOR PREDICTION

        FOCUS: Control models are used to predict control by manipulating input variables with controllers.
        EXAMPLES: Control theory, linear filters, closed-form equations, travel time models.
        

    OPERATIONS RESEARCH:
    OR1: OPTIMIZATION METHODS

        FOCUS: Mathematical methods are used to search for solutions through predefined algorithms.
        EXAMPLES: Linear and non-linear optimization, heuristics, metaheuristics, hierarchical procedures, systematic approaches.

    OR2: MULTI-SCENARIO ANALYSIS

        FOCUS: Iterative application of discrete mathematical methods with varying input variables to evaluate multiple concurrent solutions.
        EXAMPLES: Multiscenario analysis, multiobjective optimization.



    INSTRUCTIONS:
    Classify the scientific paper into ONE of the above classes (e.g., D1, PD1, PS1) based on the TITLE:" ${{ title }} " and ABSTRACT: " ${{ abstract}} "".
    If NONE of the classes are suitable, output "OTHER" followed by a brief justification of no more than 10 words. ALSO add if a method is used for DESCRIPTIVE, PREDICTIVE or PRESCRIPTIVE purpose

    OUTPUT:
    Produce an output with indicating ONLY the CLASS and the PURPOSE, without adding any other information except for "OTHER" category
       Examples:
       "P1, PREDICTIVE"
       "P1: PRESCRIPTIVE"
